import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { parseClaims } from './claim-registry'

export const renderClaims = (registry: string): string => {
  const verifiedClaims = parseClaims(registry).filter((claim) => claim.status === 'verified')
  const entries = verifiedClaims
    .map((claim) => `  ${JSON.stringify(claim.id)}: ${JSON.stringify(claim.claimEs)},`)
    .join('\n')
  return `// Generated by \`bun run claims\` from evidence/claims.toml. Do not edit.

const verifiedClaims = {
${entries}
} as const

export type ClaimId = keyof typeof verifiedClaims

export const claim = (id: ClaimId): (typeof verifiedClaims)[ClaimId] => {
  const text = verifiedClaims[id]
  if (!text) throw new Error(\`unknown or unverified claim id: \${id}\`)
  return text
}
`
}

if (import.meta.main) {
  const registryPath = resolve(import.meta.dir, '../../evidence/claims.toml')
  const outputPath = resolve(import.meta.dir, '../app/data/claims.ts')
  const registry = await readFile(registryPath, 'utf8')
  const output = renderClaims(registry)

  await mkdir(dirname(outputPath), { recursive: true })
  await writeFile(outputPath, output)
  console.log(
    `generated ${outputPath} with ${parseClaims(registry).filter((claim) => claim.status === 'verified').length} verified claims`,
  )
}
