import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { compileFromFile } from 'json-schema-to-typescript'
import { datasetIdsSource, type CatalogSource } from './dataset-ids'

const schemaPath = resolve(import.meta.dir, '../../schema/dataset.schema.json')
const catalogPath = resolve(import.meta.dir, '../app/data/source-catalog.json')
const outputPath = resolve(import.meta.dir, '../app/types/dataset.ts')

const schema = JSON.parse(readFileSync(schemaPath, 'utf8'))
const catalog = JSON.parse(readFileSync(catalogPath, 'utf8')) as { sources: CatalogSource[] }

const types = await compileFromFile(schemaPath, {
  unreachableDefinitions: true,
  bannerComment:
    '/* Generated by `bun run types` from schema/dataset.schema.json and ' +
    'app/data/source-catalog.json. Do not edit by hand. */',
  style: { semi: false, singleQuote: true, printWidth: 100 },
})

writeFileSync(outputPath, types + datasetIdsSource(schema, catalog.sources))
